[site]
title = "Hailin Ji"
description = "PhD student at Beijing Normal University."
favicon = "/favicon.svg"
last_updated = "September 20, 2026"

[author]
name = "Hailin Ji"
title = "PhD Student"
institution = "Beijing Normal University, School of Artificial Intelligence"
avatar = "/bio.png"

[social]
# Contact information (leave blank or delete to hide)

email = "jihailin@mail.bnu.edu.cn"
location = "Beijing, China"
location_url = "https://maps.google.com"
location_details = ["Beijing Normal University,", "Beijing, China"]
google_scholar = "https://scholar.google.com/citations?hl=zh-CN&user=DOgYqHgAAAAJ"
orcid = "https://orcid.org/0009-0002-3512-6730"
github = "https://github.com/zheliku"
# linkedin = "https://linkedin.com/in/jihailin"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = true

[homepage]
# Order of sections rendered on the one-page homepage
sections = [
  "about",
  "education",
  "research",
  "publications",
  # "experience",
  "awards",
  "skills",
  # "community",
  # "cv",
]

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "zh"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "zh"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Education"
type = "page"
target = "education"
href = "/education"

[[navigation]]
title = "Research"
type = "page"
target = "research"
href = "/research"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

# [[navigation]]
# title = "Experience"
# type = "page"
# target = "experience"
# href = "/experience"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Skills"
type = "page"
target = "skills"
href = "/skills"

# [[navigation]]
# title = "Community"
# type = "page"
# target = "community"
# href = "/community"

# [[navigation]]
# title = "CV"
# type = "page"
# target = "cv"
# href = "/cv"
