[[news]]
date = "2026-01"
content = "我们的工作 MomentumTouch 被人机交互顶会 CHI 2026 接收！🎉"

[[news]]
date = "2026-01"
content = "我们的工作 PhysicsHap 被图形学与虚拟现实顶会 IEEE VR 2026 接收，并推荐到了可视化与图形学顶刊 TVCG！🎉"

[[news]]
date = "2025-09"
content = "开始在北京师范大学人工智能学院攻读博士研究生（硕博连读）"

[[news]]
date = "2023-09"
content = "开始在北京师范大学人工智能学院攻读硕士研究生"
